//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.19 at 10:28:15 AM CEST 
//
package bindingClasse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Client complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Client">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nom" type="{http://www.ujf-grenoble.fr/l3m}Chaine"/>
 *         &lt;element name="prenom" type="{http://www.ujf-grenoble.fr/l3m}Chaine"/>
 *         &lt;element name="photo" type="{http://www.ujf-grenoble.fr/l3m}Photo" minOccurs="0"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tel" type="{http://www.ujf-grenoble.fr/l3m}Tel"/>
 *         &lt;element name="adresse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="points" type="{http://www.ujf-grenoble.fr/l3m}Points"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Client", propOrder = {
    "id",
    "nom",
    "prenom",
    "photo",
    "email",
    "tel",
    "adresse",
    "points"
})
@XmlRootElement(name = "client")
public class Client {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String nom;
    @XmlElement(required = true)
    protected String prenom;
    protected String photo;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String tel;
    @XmlElement(required = true)
    protected String adresse;
    protected int points;

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the nom property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNom() {
        return nom;
    }

    /**
     * Sets the value of the nom property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNom(String value) {
        this.nom = value;
    }

    /**
     * Gets the value of the prenom property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPrenom() {
        return prenom;
    }

    /**
     * Sets the value of the prenom property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPrenom(String value) {
        this.prenom = value;
    }

    /**
     * Gets the value of the photo property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * Sets the value of the photo property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPhoto(String value) {
        this.photo = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the tel property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTel() {
        return tel;
    }

    /**
     * Sets the value of the tel property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTel(String value) {
        this.tel = value;
    }

    /**
     * Gets the value of the adresse property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAdresse() {
        return adresse;
    }

    /**
     * Sets the value of the adresse property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAdresse(String value) {
        this.adresse = value;
    }

    /**
     * Gets the value of the points property.
     *
     */
    public int getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     *
     */
    public void setPoints(int value) {
        this.points = value;
    }

    @Override
    public String toString() {
        String res = "{";
        res += "\"id\": \""         + this.id + "\", ";
        res += "\"nom\": \""        + this.nom + "\", ";
        res += "\"prenom\": \""     + this.prenom + "\", ";
        res += "\"photo\": \""      + this.photo + "\", ";
        res += "\"email\": \""      + this.email + "\", ";
        res += "\"tel\": \""        + this.tel + "\", ";
        res += "\"adresse\": \""    + this.adresse + "\", ";
        res += "\"points\": \""     + this.points + "\"";
        res += "}";
        return res;
    }

}
