//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.19 at 10:30:51 AM CEST 
//
package bindingClasse;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.Map;
import java.util.Set;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Commande complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Commande">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idclient" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idPlats" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="idFilms" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="prix" type="{http://www.ujf-grenoble.fr/l3m}Prix"/>
 *         &lt;element name="adresseLivraison" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Commande", propOrder = {
    "date",
    "id",
    "idclient",
    "idPlats",
    "idFilms",
    "prix",
    "adresseLivraison"
})
@XmlRootElement(name = "commande")
public class Commande {

    @XmlElement(required = true)
    protected String date;
    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected String idclient;
    @XmlElement(required = true)
    protected List<String> idPlats;
    @XmlElement(required = true)
    protected List<String> idFilms;
    protected double reduction;
    protected double prix;
    @XmlElement(required = true)
    protected String adresseLivraison;

    /**
     * Gets the value of the date property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the idclient property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIdclient() {
        return idclient;
    }

    /**
     * Sets the value of the idclient property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setIdclient(String value) {
        this.idclient = value;
    }

    /**
     * Gets the value of the idPlats property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the idPlats property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdPlats().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     *
     *
     */
    public List<String> getIdPlats() {
        if (idPlats == null) {
            idPlats = new ArrayList<String>();
        }
        return this.idPlats;
    }

    public void setIdPlats(List<String> idPlats) {
        this.idPlats = idPlats;
    }

    /**
     * Gets the value of the idFilms property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the idFilms property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdFilms().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     *
     *
     */
    public List<String> getIdFilms() {
        if (idFilms == null) {
            idFilms = new ArrayList<String>();
        }
        return this.idFilms;
    }

    public void setIdFilms(List<String> idFilms) {
        this.idFilms = idFilms;
    }

    public double getReduction() {
        return reduction;
    }

    public void setReduction(double reduction) {
        this.reduction = reduction;
    }
    
    
    /**
     * Gets the value of the prix property.
     *
     */
    public double getPrix() {
        return prix;
    }

    /**
     * Sets the value of the prix property.
     *
     */
    public void setPrix(double value) {
        this.prix = value;
    }

    /**
     * Gets the value of the adresseLivraison property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAdresseLivraison() {
        return adresseLivraison;
    }

    /**
     * Sets the value of the adresseLivraison property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAdresseLivraison(String value) {
        this.adresseLivraison = value;
    }

    /**
     * Affichage plus convival et exploitable de la commande
     *
     * @return une string sous forme JSON de la commande
     */
    @Override
    public String toString() {
        String prix_round = new DecimalFormat("##.##").format(this.prix);
        prix_round = prix_round.replace(",", ".");
        
        String reduction_round = new DecimalFormat("##.##").format(this.reduction);
        reduction_round = reduction_round.replace(",", ".");
        
        Double total =  this.prix - this.reduction;
        
        String json_plats = "";

        ListIterator<String> plat = this.idPlats.listIterator();
        while (plat.hasNext()) {
            String str = plat.next();
            int iend = str.indexOf(":");

            if (plat.hasNext()) {
                json_plats += "{"
                        + "\"id\" : " + Integer.parseInt(str.substring(0, iend)) + ", "
                        + "\"quantite\" : " + Integer.parseInt(str.substring(iend + 1, str.length()))
                        + "} ,";
            } else {
                json_plats += "{"
                        + "\"id\" : " + Integer.parseInt(str.substring(0, iend)) + ", "
                        + "\"quantite\" : " + Integer.parseInt(str.substring(iend + 1, str.length()))
                        + "} ";
            }
        }

        String res = "{";
        res += "\"id\": " + this.id + ", ";
        res += "\"idclient\": \"" + this.idclient + "\", ";
        res += "\"date\": \"" + this.date + "\", ";
        res += "\"idFilms\": " + this.idFilms + ", ";
        res += "\"idPlats\": [" + json_plats + "], ";
        res += "\"reduction\": " + reduction_round + ", ";
        res += "\"sous-total\": " + prix_round + ", ";
        res += "\"total\": " + total + ", ";
        res += "\"adresseLivraison\": \"" + this.adresseLivraison + "\"";
        res += "}";
        return res;
    }
}
