//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.19 at 10:30:30 AM CEST 
//


package bindingClasse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ingredient.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Ingredient">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Tomate"/>
 *     &lt;enumeration value="Champignon"/>
 *     &lt;enumeration value="Mozzarella"/>
 *     &lt;enumeration value="Patate"/>
 *     &lt;enumeration value="Saumon"/>
 *     &lt;enumeration value="Boeuf"/>
 *     &lt;enumeration value="Bacon"/>
 *     &lt;enumeration value="Thon"/>
 *     &lt;enumeration value="Oeuf"/>
 *     &lt;enumeration value="Salade"/>
 *     &lt;enumeration value="Emmental"/>
 *     &lt;enumeration value="Chocolat"/>
 *     &lt;enumeration value="Fraise"/>
 *     &lt;enumeration value="Banane"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Ingredient")
@XmlEnum
public enum Ingredient {

    @XmlEnumValue("Tomate")
    TOMATE("Tomate"),
    @XmlEnumValue("Champignon")
    CHAMPIGNON("Champignon"),
    @XmlEnumValue("Mozzarella")
    MOZZARELLA("Mozzarella"),
    @XmlEnumValue("Champignons")
    CHAMPIGNONS("Champignons"),
    @XmlEnumValue("Oignons")
    OIGNONS("Oignons"),
    @XmlEnumValue("Olives")
    OLIVES("Olives"),
    @XmlEnumValue("Poivrons")
    POIVRONS("Poivrons"),
    @XmlEnumValue("Merguez")
    MERQUEZ("Merguez"),
    @XmlEnumValue("Patate")
    PATATE("Patate"),
    @XmlEnumValue("Saumon")
    SAUMON("Saumon"),
    @XmlEnumValue("Boeuf")
    BOEUF("Boeuf"),
    @XmlEnumValue("Jambon")
    JAMBON("Jambon"),
    @XmlEnumValue("Thon")
    THON("Thon"),
    @XmlEnumValue("Oeuf")
    OEUF("Oeuf"),
    @XmlEnumValue("Salade")
    SALADE("Salade"),
    @XmlEnumValue("Emmental")
    EMMENTAL("Emmental"),
    @XmlEnumValue("Chocolat")
    CHOCOLAT("Chocolat"),
    @XmlEnumValue("Fraise")
    FRAISE("Fraise"),
    @XmlEnumValue("Banane")
    BANANE("Banane"),
    @XmlEnumValue("Cola")
    COLA("Cola"),
    @XmlEnumValue("Eau")
    EAU("Eau"),
    @XmlEnumValue("Jus")
    JUS("Jus");
    private final String value;

    Ingredient(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Ingredient fromValue(String v) {
        for (Ingredient c: Ingredient.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
