//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.19 at 10:30:30 AM CEST 
//
package bindingClasse;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Plats complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Plats">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plat" type="{http://www.ujf-grenoble.fr/l3m}Plat" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Plats", propOrder = {
    "plats"
})
@XmlRootElement(name = "plats")
public class Plats {

    @XmlElement(name = "plat", required = true)
    protected List<Plat> plats;

    /**
     * Gets the value of the plats property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the plats property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlats().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Plat }
     *
     *
     */
    public List<Plat> getPlats() {
        if (plats == null) {
            plats = new ArrayList<>();
        }
        return this.plats;
    }

    public Double getPrixPlat(String reference) {
        Double prix = 0.0;

        Iterator<Plat> platsIterator = plats.listIterator();

        while (platsIterator.hasNext()) {
            Plat value = platsIterator.next();
            if (value.getId().equals(reference)) {
                prix = value.getPrix();
                return prix;
            }
        }

        return prix;
    }

    public void setPlats(List<Plat> plats) {
        this.plats = plats;
    }

}
